/*
 * Using a playback file generated by the python file in this dir,
 * play back the game move by move.
 * 
 * Author: Evan Rittenhouse
 */

#include <stdio.h>
#include <stdlib.h>
#include "../board.h"

void printBoard(struct board *board);

int main(int numArgs, char** args)
{
    if (numArgs < 2)
    {
        printf("Please provide the playback file you want to play back.\n");
        return 1;
    }

    FILE *playbackFile;
    int pos[2];
    struct board gameBoard;

    playbackFile = fopen(args[1], "r");

    if (playbackFile == NULL)
    {
        printf("Could not open file %s!\n", args[1]);
        return 1;
    }

    initBoard(&gameBoard);
    printf("Initial board\n\n");
    printBoard(&gameBoard);
    printf("\nPress [ENTER] to continue...");
    getchar();
    system("clear");

    // Start reading the file
    while (!feof(playbackFile))
    {
        fscanf(playbackFile, "(%d, %d)\n", pos, pos + 1);

        if (pos[0] == -1 || pos[1] == -1)
        {
            printf("Player %d cannot move.\n", gameBoard.whoseMove);
            gameBoard.whoseMove = gameBoard.whoseMove ^ 3;
        }
        else
        {
            printf("Player %d plays at (%d, %d)\n\n", gameBoard.whoseMove, pos[0], pos[1]);
            placePiece(&gameBoard, pos);
        }

        printBoard(&gameBoard);

        printf("\nPress [ENTER] to continue...");
        getchar();
        system("clear");
    }

    fclose(playbackFile);
    return 0;
}

void printBoard(struct board *board)
{
	int i, j;

	if (board->whoseMove == 1)
	{
		printf("White's turn");
	}
	else
	{
		printf("Black's turn");
	}

	printf("\t| White score: %d\t| Black score: %d\n", board->whiteScore, board->blackScore);

	for (i = 0; i < 32; i++)
	{
		for (j = 0; j < 32; j++)
		{
			switch(board->spaces[i][j])
			{
				case 0:
					printf("* ");
					break;
				case 1:
					printf("w ");
					break;
				case 2:
					printf("b ");
					break;
			}
		}

		printf("\n");
	}
}